// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelectAds.proto

package io.bittiger.adindex;

/**
 * Protobuf type {@code adindex.AdsRequest}
 */
public  final class AdsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:adindex.AdsRequest)
    AdsRequestOrBuilder {
  // Use AdsRequest.newBuilder() to construct.
  private AdsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdsRequest() {
    query_ = java.util.Collections.emptyList();
    deviceId_ = "";
    deviceIp_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AdsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              query_ = new java.util.ArrayList<io.bittiger.adindex.Query>();
              mutable_bitField0_ |= 0x00000001;
            }
            query_.add(
                input.readMessage(io.bittiger.adindex.Query.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceIp_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        query_ = java.util.Collections.unmodifiableList(query_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.bittiger.adindex.SearchAds.internal_static_adindex_AdsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.bittiger.adindex.SearchAds.internal_static_adindex_AdsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.bittiger.adindex.AdsRequest.class, io.bittiger.adindex.AdsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int QUERY_FIELD_NUMBER = 1;
  private java.util.List<io.bittiger.adindex.Query> query_;
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  public java.util.List<io.bittiger.adindex.Query> getQueryList() {
    return query_;
  }
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  public java.util.List<? extends io.bittiger.adindex.QueryOrBuilder> 
      getQueryOrBuilderList() {
    return query_;
  }
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  public int getQueryCount() {
    return query_.size();
  }
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  public io.bittiger.adindex.Query getQuery(int index) {
    return query_.get(index);
  }
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  public io.bittiger.adindex.QueryOrBuilder getQueryOrBuilder(
      int index) {
    return query_.get(index);
  }

  public static final int DEVICEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>string deviceId = 2;</code>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEIP_FIELD_NUMBER = 3;
  private volatile java.lang.Object deviceIp_;
  /**
   * <code>string deviceIp = 3;</code>
   */
  public java.lang.String getDeviceIp() {
    java.lang.Object ref = deviceIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceIp_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceIp = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIpBytes() {
    java.lang.Object ref = deviceIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < query_.size(); i++) {
      output.writeMessage(1, query_.get(i));
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
    }
    if (!getDeviceIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceIp_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < query_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, query_.get(i));
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
    }
    if (!getDeviceIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceIp_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.bittiger.adindex.AdsRequest)) {
      return super.equals(obj);
    }
    io.bittiger.adindex.AdsRequest other = (io.bittiger.adindex.AdsRequest) obj;

    boolean result = true;
    result = result && getQueryList()
        .equals(other.getQueryList());
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    result = result && getDeviceIp()
        .equals(other.getDeviceIp());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getQueryCount() > 0) {
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQueryList().hashCode();
    }
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + DEVICEIP_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceIp().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.bittiger.adindex.AdsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bittiger.adindex.AdsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.bittiger.adindex.AdsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.bittiger.adindex.AdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.bittiger.adindex.AdsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code adindex.AdsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:adindex.AdsRequest)
      io.bittiger.adindex.AdsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.bittiger.adindex.SearchAds.internal_static_adindex_AdsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.bittiger.adindex.SearchAds.internal_static_adindex_AdsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.bittiger.adindex.AdsRequest.class, io.bittiger.adindex.AdsRequest.Builder.class);
    }

    // Construct using io.bittiger.adindex.AdsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQueryFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (queryBuilder_ == null) {
        query_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        queryBuilder_.clear();
      }
      deviceId_ = "";

      deviceIp_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.bittiger.adindex.SearchAds.internal_static_adindex_AdsRequest_descriptor;
    }

    public io.bittiger.adindex.AdsRequest getDefaultInstanceForType() {
      return io.bittiger.adindex.AdsRequest.getDefaultInstance();
    }

    public io.bittiger.adindex.AdsRequest build() {
      io.bittiger.adindex.AdsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.bittiger.adindex.AdsRequest buildPartial() {
      io.bittiger.adindex.AdsRequest result = new io.bittiger.adindex.AdsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (queryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          query_ = java.util.Collections.unmodifiableList(query_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.query_ = query_;
      } else {
        result.query_ = queryBuilder_.build();
      }
      result.deviceId_ = deviceId_;
      result.deviceIp_ = deviceIp_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.bittiger.adindex.AdsRequest) {
        return mergeFrom((io.bittiger.adindex.AdsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.bittiger.adindex.AdsRequest other) {
      if (other == io.bittiger.adindex.AdsRequest.getDefaultInstance()) return this;
      if (queryBuilder_ == null) {
        if (!other.query_.isEmpty()) {
          if (query_.isEmpty()) {
            query_ = other.query_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQueryIsMutable();
            query_.addAll(other.query_);
          }
          onChanged();
        }
      } else {
        if (!other.query_.isEmpty()) {
          if (queryBuilder_.isEmpty()) {
            queryBuilder_.dispose();
            queryBuilder_ = null;
            query_ = other.query_;
            bitField0_ = (bitField0_ & ~0x00000001);
            queryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQueryFieldBuilder() : null;
          } else {
            queryBuilder_.addAllMessages(other.query_);
          }
        }
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getDeviceIp().isEmpty()) {
        deviceIp_ = other.deviceIp_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.bittiger.adindex.AdsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.bittiger.adindex.AdsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.bittiger.adindex.Query> query_ =
      java.util.Collections.emptyList();
    private void ensureQueryIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        query_ = new java.util.ArrayList<io.bittiger.adindex.Query>(query_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.bittiger.adindex.Query, io.bittiger.adindex.Query.Builder, io.bittiger.adindex.QueryOrBuilder> queryBuilder_;

    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public java.util.List<io.bittiger.adindex.Query> getQueryList() {
      if (queryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(query_);
      } else {
        return queryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public int getQueryCount() {
      if (queryBuilder_ == null) {
        return query_.size();
      } else {
        return queryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public io.bittiger.adindex.Query getQuery(int index) {
      if (queryBuilder_ == null) {
        return query_.get(index);
      } else {
        return queryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder setQuery(
        int index, io.bittiger.adindex.Query value) {
      if (queryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryIsMutable();
        query_.set(index, value);
        onChanged();
      } else {
        queryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder setQuery(
        int index, io.bittiger.adindex.Query.Builder builderForValue) {
      if (queryBuilder_ == null) {
        ensureQueryIsMutable();
        query_.set(index, builderForValue.build());
        onChanged();
      } else {
        queryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder addQuery(io.bittiger.adindex.Query value) {
      if (queryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryIsMutable();
        query_.add(value);
        onChanged();
      } else {
        queryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder addQuery(
        int index, io.bittiger.adindex.Query value) {
      if (queryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryIsMutable();
        query_.add(index, value);
        onChanged();
      } else {
        queryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder addQuery(
        io.bittiger.adindex.Query.Builder builderForValue) {
      if (queryBuilder_ == null) {
        ensureQueryIsMutable();
        query_.add(builderForValue.build());
        onChanged();
      } else {
        queryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder addQuery(
        int index, io.bittiger.adindex.Query.Builder builderForValue) {
      if (queryBuilder_ == null) {
        ensureQueryIsMutable();
        query_.add(index, builderForValue.build());
        onChanged();
      } else {
        queryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder addAllQuery(
        java.lang.Iterable<? extends io.bittiger.adindex.Query> values) {
      if (queryBuilder_ == null) {
        ensureQueryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, query_);
        onChanged();
      } else {
        queryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder clearQuery() {
      if (queryBuilder_ == null) {
        query_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        queryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public Builder removeQuery(int index) {
      if (queryBuilder_ == null) {
        ensureQueryIsMutable();
        query_.remove(index);
        onChanged();
      } else {
        queryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public io.bittiger.adindex.Query.Builder getQueryBuilder(
        int index) {
      return getQueryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public io.bittiger.adindex.QueryOrBuilder getQueryOrBuilder(
        int index) {
      if (queryBuilder_ == null) {
        return query_.get(index);  } else {
        return queryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public java.util.List<? extends io.bittiger.adindex.QueryOrBuilder> 
         getQueryOrBuilderList() {
      if (queryBuilder_ != null) {
        return queryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(query_);
      }
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public io.bittiger.adindex.Query.Builder addQueryBuilder() {
      return getQueryFieldBuilder().addBuilder(
          io.bittiger.adindex.Query.getDefaultInstance());
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public io.bittiger.adindex.Query.Builder addQueryBuilder(
        int index) {
      return getQueryFieldBuilder().addBuilder(
          index, io.bittiger.adindex.Query.getDefaultInstance());
    }
    /**
     * <code>repeated .adindex.Query query = 1;</code>
     */
    public java.util.List<io.bittiger.adindex.Query.Builder> 
         getQueryBuilderList() {
      return getQueryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.bittiger.adindex.Query, io.bittiger.adindex.Query.Builder, io.bittiger.adindex.QueryOrBuilder> 
        getQueryFieldBuilder() {
      if (queryBuilder_ == null) {
        queryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.bittiger.adindex.Query, io.bittiger.adindex.Query.Builder, io.bittiger.adindex.QueryOrBuilder>(
                query_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        query_ = null;
      }
      return queryBuilder_;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string deviceId = 2;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceId = 2;</code>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 2;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 2;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceIp_ = "";
    /**
     * <code>string deviceIp = 3;</code>
     */
    public java.lang.String getDeviceIp() {
      java.lang.Object ref = deviceIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceIp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      java.lang.Object ref = deviceIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceIp = 3;</code>
     */
    public Builder setDeviceIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceIp = 3;</code>
     */
    public Builder clearDeviceIp() {
      
      deviceIp_ = getDefaultInstance().getDeviceIp();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceIp = 3;</code>
     */
    public Builder setDeviceIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceIp_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:adindex.AdsRequest)
  }

  // @@protoc_insertion_point(class_scope:adindex.AdsRequest)
  private static final io.bittiger.adindex.AdsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.bittiger.adindex.AdsRequest();
  }

  public static io.bittiger.adindex.AdsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdsRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdsRequest>() {
    public AdsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdsRequest> getParserForType() {
    return PARSER;
  }

  public io.bittiger.adindex.AdsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

