// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelectAds.proto

package io.bittiger.adindex;

public interface AdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adindex.AdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  java.util.List<io.bittiger.adindex.Query> 
      getQueryList();
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  io.bittiger.adindex.Query getQuery(int index);
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  int getQueryCount();
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  java.util.List<? extends io.bittiger.adindex.QueryOrBuilder> 
      getQueryOrBuilderList();
  /**
   * <code>repeated .adindex.Query query = 1;</code>
   */
  io.bittiger.adindex.QueryOrBuilder getQueryOrBuilder(
      int index);

  /**
   * <code>string deviceId = 2;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string deviceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string deviceIp = 3;</code>
   */
  java.lang.String getDeviceIp();
  /**
   * <code>string deviceIp = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIpBytes();
}
