// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelectAds.proto

package io.bittiger.adindex;

public interface QueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adindex.Query)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string term = 1;</code>
   */
  java.util.List<java.lang.String>
      getTermList();
  /**
   * <code>repeated string term = 1;</code>
   */
  int getTermCount();
  /**
   * <code>repeated string term = 1;</code>
   */
  java.lang.String getTerm(int index);
  /**
   * <code>repeated string term = 1;</code>
   */
  com.google.protobuf.ByteString
      getTermBytes(int index);
}
